theme = "gruvbox_original_dark_hard"

[editor]
line-number = "relative"
true-color = true

[keys.insert]
up ="no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[editor.cursor-shape]
insert = "bar"
